[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 8000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/:apiKey/v1/:randomId"
  to = "/.netlify/functions/raw"
  status = 200
  force = true
